USE MASTER;
GO
CREATE DATABASE MICROSERVICE;
GO
USE MICROSERVICE;
GO
CREATE TABLE TAB_ENTRY (
   ID UNIQUEIDENTIFIER NOT NULL,
   USER_NM VARCHAR(20) NOT NULL,
   ENTRY_DT DATETIME NOT NULL,
   ENTRY_VL DECIMAL(10,2) NOT NULL,
   ENTRY_TP CHAR NOT NULL,
   ACCOUNT_DS VARCHAR(20) NOT NULL,
   ENTRY_DS VARCHAR(100),
   CREATED_AT_DT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);